/**
* ────────────────────────────────────────────────────────────────────────────────────────────────
* MockHttpResponseGenerator class-
* Purpose: Mock class to cover HTTPresponse.
* Used by Test Class: BpointFlexiPaymentControllerTest
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Bharat J   <bharat.joshi@psagtechnologies.com>
* @version        1.0
* @created        2019-08-23
* @systemLayer    Test, Mock
* ────────────────────────────────────────────────────────────────────────────────────────────────── */
@isTest
global class MockHttpResponseGenerator implements HttpCalloutMock {
    // Implement this interface method
    global HTTPResponse respond(HTTPRequest req) {
        // Optionally, only send a mock response for a specific endpoint
        // and method.
        System.assertEquals('http://example.com/example/test', req.getEndpoint());
        System.assertEquals('GET', req.getMethod());
        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"example":"test"}');
        res.setStatusCode(200);
        return res;
    }
}