/**
 * Created by PedroRusooli on the 25th of Never.
 */

public with sharing class TheBetootaAdvocate {

    @InvocableMethod
    public static void activateFluxCapacitor(List<Id> orderIds)
    {
        // Boolean fluxCapacitor = true;
        // List PTs =[select id from Payment_Transaction__c
        // where order__c in :orderIds];
        // dml PTs;
        // flux capacitors don't exist so just do nothing
    }
}